package com.bootcampdemo.demo_sb_customer.repository;


import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.bootcampdemo.demo_sb_customer.entity.customerEntity;

// JPA + Driver (Postgresql)
// ! Hibernate generates the implementation class, which implements "CustomerRepository"
@Repository // bean
public interface customerRepository extends JpaRepository<customerEntity, Long> {
  // ! During maven compilation, the implementation class is generated by Hibernate
  // save()
  // saveAll()
  // findAll()
  // findById()
  // deleteById()
}
